import { AlertTriangle, ArrowLeft, CheckCircle2, ClipboardCheck, Clock3, MapPin, ShieldAlert, Sparkles, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { formatDate, severityStyles, statuses, statusStyles, urgencyTone } from '../utils/issues'

export default function IssueDetail({ issues, onVerify, onUpdate }) {
  const { issueId } = useParams()
  const issue = issues.find((item) => item.id === issueId)
  if (!issue) return <main className="shell py-20 text-center"><h1 className="heading text-3xl">This report isn’t here.</h1><p className="muted mt-2">It may have been removed from this browser.</p><Link className="btn-primary mt-6" to="/dashboard">Back to dashboard</Link></main>
  const currentStep = statuses.indexOf(issue.status)
  return <main className="shell max-w-6xl py-8 sm:py-12"><Link to="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft size={16} />Back to issue dashboard</Link><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section className="space-y-6"><div className="panel overflow-hidden"><img src={issue.image} alt="Civic issue" className="h-64 w-full object-cover sm:h-80" /><div className="p-5 sm:p-7"><div className="flex flex-wrap items-center gap-2"><span className={`badge ${severityStyles[issue.severity]}`}>{issue.severity}</span><span className={`badge ${statusStyles[issue.status]}`}>{issue.status}</span><span className="text-xs font-semibold text-slate-500">{issue.id}</span></div><h1 className="heading mt-4 text-2xl sm:text-3xl">{issue.title}</h1><div className="mt-3 flex items-start gap-2 text-sm text-slate-400"><MapPin className="mt-0.5 shrink-0 text-mint" size={17} />{issue.location}</div><p className="mt-5 leading-relaxed text-slate-300">{issue.description}</p><div className="mt-6 grid gap-3 border-t border-line pt-5 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Suggested department</p><p className="mt-1 text-sm font-semibold text-sky-100">{issue.department}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Reported</p><p className="mt-1 text-sm font-semibold text-slate-200">{formatDate(issue.createdAt)}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Community</p><p className="mt-1 flex items-center gap-1 text-sm font-semibold text-slate-200"><Users size={15} />{issue.verifications} verified</p></div></div></div></div>
      <section className="panel p-5 sm:p-6"><p className="section-label"><Sparkles size={14} />{issue.ai?.isFallback === false ? 'Gemini Analysis' : 'Demo AI Analysis'}</p><h2 className="heading text-xl">An actionable civic brief.</h2><p className="mt-3 leading-relaxed text-slate-300">{issue.ai.complaintSummary}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-line bg-ink/60 p-4"><Clock3 className="mb-2 text-sky-300" size={18} /><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Estimated resolution</p><p className="mt-1 text-sm font-semibold text-slate-100">{issue.ai.estimatedResolutionTime}</p></div><div className="rounded-xl border border-line bg-ink/60 p-4"><ClipboardCheck className="mb-2 text-mint" size={18} /><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Duplicate signals</p><p className="mt-1 text-sm font-semibold text-slate-100">{issue.ai.duplicateKeywords.join(' · ')}</p></div></div>{issue.ai.safetyWarning && <div className="mt-4 flex gap-3 rounded-xl border border-amber-500/25 bg-amber-500/[.07] p-4 text-sm leading-relaxed text-amber-100"><ShieldAlert className="shrink-0" size={19} /><span>{issue.ai.safetyWarning}</span></div>}</section>
      <section className="panel p-5 sm:p-6"><p className="section-label"><CheckCircle2 size={14} />AI action plan</p><div className="space-y-3">{issue.ai.actionPlan.map((action, index) => <div className="flex gap-3" key={action}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-civic/10 text-xs font-black text-civic">0{index + 1}</span><p className="pt-1 text-sm leading-relaxed text-slate-300">{action}</p></div>)}</div></section>
    </section>
    <aside className="space-y-5"><section className="panel p-5"><p className="text-sm font-bold text-slate-100">AI urgency score</p><div className="mt-4 flex items-end gap-3"><b className="text-5xl text-white">{issue.urgencyScore}</b><span className="mb-2 text-sm text-slate-500">out of 100</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-700"><div className={`h-full rounded-full ${urgencyTone(issue.urgencyScore)}`} style={{ width: `${issue.urgencyScore}%` }} /></div></section>
      <section className="panel p-5"><p className="text-sm font-bold text-slate-100">Resolution timeline</p><div className="mt-5 space-y-0">{statuses.map((status, index) => <div className="relative flex gap-3 pb-5 last:pb-0" key={status}>{index < statuses.length - 1 && <span className={`absolute left-[9px] top-5 h-[calc(100%-4px)] w-px ${index < currentStep ? 'bg-mint/50' : 'bg-line'}`} />}<span className={`z-10 mt-0.5 h-5 w-5 rounded-full border-4 ${index <= currentStep ? 'border-mint bg-mint' : 'border-slate-700 bg-panel'}`} /><div><p className={`text-sm font-semibold ${index <= currentStep ? 'text-slate-100' : 'text-slate-500'}`}>{status}</p>{index === currentStep && <p className="mt-0.5 text-xs text-mint">Current stage</p>}</div></div>)}</div></section>
      <section className="panel p-5"><p className="text-sm font-bold text-slate-100">Community verification</p><p className="muted mt-2">Confirm you have seen this issue. Every verification improves the report’s credibility.</p><button className="btn-primary mt-4 w-full" onClick={() => onVerify(issue.id)}><CheckCircle2 size={16} />Verify this issue ({issue.verifications})</button></section>
      <section className="panel border-sky-400/20 p-5"><p className="section-label">Demo workflow actions</p><p className="mb-3 text-xs leading-relaxed text-slate-500">Status changes below are saved only in this browser.</p><label className="text-xs font-bold uppercase tracking-wider text-slate-500">Update status<select className="input mt-2" value={issue.status} onChange={(e) => onUpdate(issue.id, { status: e.target.value })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label>{issue.isDuplicate && <p className="mt-3 flex gap-2 text-sm text-amber-200"><AlertTriangle size={16} />Marked as potential duplicate</p>}</section>
    </aside></div></main>
}

