import { Landmark, MapPin, Tags } from 'lucide-react'
import { useEffect, useState } from 'react'
const samples = [
  { title: 'Deep pothole near Whitefield Main Road', location: 'Whitefield Main Road, near Agara Farm Junction', category: 'Pothole / Road Damage', department: 'BBMP Road Infrastructure', score: 94, verified: 70 },
  { title: 'Water leak beside Varthur school road', location: 'Varthur School Road, near Chrysalis High', category: 'Water Leakage', department: 'BWSSB Water Supply', score: 81, verified: 42 },
  { title: 'Open drainage near market entrance', location: 'Varthur Market Road, opposite vegetable market', category: 'Drainage Issue', department: 'BBMP Storm Water Drain', score: 89, verified: 55 },
]
function TypeText({ text, delay, speed, run }) { const [shown, setShown] = useState(''); useEffect(() => { let interval; const timer = setTimeout(() => { let index = 0; interval = setInterval(() => { index += 1; setShown(text.slice(0, index)); if (index >= text.length) clearInterval(interval) }, speed) }, delay); return () => { clearTimeout(timer); clearInterval(interval) } }, [text, delay, speed, run]); return <>{shown}</> }
function CountScore({ target, run }) { const [score, setScore] = useState(0); useEffect(() => { let frame; const timer = setTimeout(() => { const start = performance.now(); const step = (time) => { const progress = Math.min((time - start) / 600, 1); setScore(Math.round(target * (1 - (1 - progress) ** 3))); if (progress < 1) frame = requestAnimationFrame(step) }; frame = requestAnimationFrame(step) }, 2800); return () => { clearTimeout(timer); cancelAnimationFrame(frame) } }, [target, run]); return score }
export default function HeroAnalysisCard() { const [run, setRun] = useState(0); const sample = samples[run % samples.length]; const score = CountScore(sample.score, run); useEffect(() => { const timer = setInterval(() => setRun((value) => value + 1), 8000); return () => clearInterval(timer) }, []); return <article key={run} className="hero-ai-card"><div className="hero-ai-header"><div className="flex items-center gap-2"><span className="analysis-live-dot" /><span className="data-mono text-[11px] text-slate-400"><TypeText text="AI Analysis · Live" delay={300} speed={40} run={run} /></span></div><span className={`data-mono text-sm font-bold ${score >= 80 ? 'text-danger' : 'text-amber'}`}>{score}/100</span></div><div className="hero-ai-content"><h2 className="font-display text-[15px] font-semibold leading-5 text-slate-100"><TypeText text={sample.title} delay={900} speed={25} run={run} /><span className="type-cursor" /></h2><div className="mt-3 space-y-2.5 text-[13px]"><p className="hero-ai-row" style={{ animationDelay: '2200ms' }}><MapPin className="mt-0.5 shrink-0 text-civic" size={15} /><span className="text-slate-400">Location:</span><span className="text-slate-100">{sample.location}</span></p><p className="hero-ai-row" style={{ animationDelay: '2350ms' }}><Tags className="shrink-0 text-civic" size={15} /><span className="text-slate-400">Category:</span><span className="text-slate-100">{sample.category}</span></p><p className="hero-ai-row" style={{ animationDelay: '2500ms' }}><Landmark className="shrink-0 text-civic" size={15} /><span className="text-slate-400">Routes to:</span><span className="text-slate-100">{sample.department}</span></p></div></div><div className="hero-ai-footer"><p className="data-mono text-xs font-semibold text-civic">✓ {sample.verified} neighbours verified this issue</p></div></article> }
